### ISSUE TITLE
broken link for Voyage Management Microservice docs

### ISSUE THREAD

**Issue by josiemundi** [ibm-cloud-architecture/refarch-kc-ms#39]
I was trying to look for the docs on the Voyage management microservice and it directs me to the following link, which seems not to work. 

https://ibm-cloud-architecture.github.io/refarch-kc-ms/voyagems.md

**Comment by jesusmah** [comment]
Hi @josiemundi, could you let me know where did you get redirected to the link above so that I can look at there to change the hyperlink please?

Thank you

**Comment by jesusmah** [comment]
Is it when you click in the left hand side panel of the github book view?

**Comment by jesusmah** [comment]
Fixed with #41
