### ISSUE TITLE
Voyages ms cannot connect to SSL enabled Kafka

### ISSUE THREAD

**Issue by djones6** [ibm-cloud-architecture/refarch-kc-ms#54]
Since the Appsody repackaging (#50) I have discovered that the voyages microservice is not connecting to Event Streams successfully.  It fails with an 'SSL error' (without any other useful information).  I'm debugging this locally but don't have a solution yet.  I suspect this applies to any SSL-enabled Kafka (I don't have another one to hand to check).

In the meantime, deployments against SSL enabled Kafkas should use version `0.1.25`.

**Comment by djones6** [comment]
Submitted a fix for this in the `nodejs-express` Appsody stack: https://github.com/appsody/stacks/pull/838

Turns out, the slim image used to build the application was missing the `ca-certificates` package, which meant no public certificate verification would work.  The managed Event Streams on IBM Cloud provides a properly signed certificate, which is why we do not need to provide the certificate to the client, however this only works if the CA roots are installed in the image.

**Comment by djones6** [comment]
This is now fixed in `appsody/nodejs-express:0.4.13`, so if we re-run the CI, the service should work properly with Event Streams again.

**Comment by osowski** [comment]
Multitasking at the moment, but was able to kick off another build via https://github.com/ibm-cloud-architecture/refarch-kc-ms/commit/8ed8440988592ef51c772cdbece4f4bd411014ba. You should be able to see `voyages:0.1.31` based on the updated Appsody stack now.
